### ISSUE TITLE
question about what belongs in this repo

### ISSUE THREAD

**Issue by magland** [flatironinstitute/spikesortercomparison#2]
@alex - I've been struggling to find a place to put down ideas without emailing a large group of people. This repo seems like it has the potential to be such a place. For example, I'd like to sketch out ideas about the design of the website. Would we have subdirectories where such entries can go? Just trying to get a vision for how you expect this repo to be organized and what the content/goals are.

**Comment by ahbarnett** [comment]
Hi Jeremy - good idea - I hadn't thought about subdirs, but just make one. I'll add you as a dev for this repo. Having some design docs/notes here is good.
