### ISSUE TITLE
linked gitter community?

### ISSUE THREAD

**Issue by magland** [flatironinstitute/spikesortercomparison#3]
I propose that we give gitter a try (the CaImAn developers use it I believe). We can create a new gitter community attached to this github repo. I have submitted a request to the flatiron github organization admin to allow gitter access to the necessary repo info to perform such a link.

This could be a mechanism for the community to comment on our efforts without doing it through pull requests or github issues.

Shall we give it a try?

**Comment by magland** [comment]
It seems that the admins of the flatironinstitute organization would need to do something like the following to allow the link:

https://gitter.zendesk.com/hc/en-us/articles/202460552-Why-isn-t-my-GitHub-organisation-appearing-

**Comment by ahbarnett** [comment]
neurofinder also used gitter; looked like sensible discussions. So, I'm in favor. (Certainly prefer to slack, since I can't seem to stay onto of that one). We need to chat w/ SCC. Of course, we can always move to a personal github repo, but what we're trying to do is institutional.

**Comment by magland** [comment]
I created and linked a gitter room. It was a bit confusing because communities can either be associated with git repo's or git organizations. But of course we want it to be associated with a repo within an organization. The best I could do was to create a community associated with flatironinstitute (organization) and then within it create a room associated with spikesortercomparison repo. I guess this means we can only have a single room under the umbrella of spikesortingcomparison. It would be nice to have individual rooms for metrics, sorting-wrappers, website-design, etc. Not sure what is the best way to organize this.

But there is now a badge on the README of this repo that links to the gitter discussion.
